[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "flask-ngrok>=0.0.25",
    "flask>=3.1.0",
    "pytelegrambotapi>=4.26.0",
    "yt-dlp>=2025.2.19",
]
